import JsonLd from "@/components/JsonLd";
import { SITE_DATASET } from "@/data/siteDataset";
import { ContentSection, CoverageHeader, CoveragePageFrame, EvidenceNote, Metrics, RelatedLinks, SourceLink, formatCoverageDate } from "@/features/seo-coverage/CoveragePage";
import { getCoverageCities, getCoverageReviewFacts } from "@/server/coverage/catalog";
import { absoluteUrl, createPageMetadata, SITE_NAME } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Pakistan 5G Rollout Report: August 2026", description: "A dated baseline of 932 Jazz, Zong and Ufone / Onic provider-published 5G site records, with city totals and source audit findings.", path: "/reports/pakistan-5g-rollout-august-2026" });

export default function AugustRolloutReportPage() {
  const facts = getCoverageReviewFacts();
  const cities = getCoverageCities();
  return <CoveragePageFrame>
    <JsonLd data={{ "@context": "https://schema.org", "@type": "Report", name: "Pakistan 5G rollout report: August 2026", description: "A dated baseline of provider-published Pakistan 5G site records and their source review.", url: absoluteUrl("/reports/pakistan-5g-rollout-august-2026"), datePublished: facts.reviewedAt, dateModified: facts.reviewedAt, publisher: { "@type": "Organization", name: SITE_NAME, url: absoluteUrl("/") }, about: { "@type": "Dataset", name: SITE_DATASET.name } }} />
    <CoverageHeader eyebrow="Dated rollout baseline" title="Pakistan 5G rollout report: August 2026" description={`A reproducible summary of ${facts.totalSites} provider-published Jazz, Zong and Ufone / Onic site records, their major city groups, and the source conditions found during review.`} breadcrumbs={[{ name: "Home", href: "/" }, { name: "Coverage", href: "/coverage" }, { name: "August 2026 report", href: "/reports/pakistan-5g-rollout-august-2026" }]} primaryHref="/data/sites.geojson" primaryLabel="Download the GeoJSON" />
    <Metrics items={[{ label: "All records", value: facts.totalSites }, ...SITE_DATASET.providers.map((provider) => ({ label: provider.name, value: provider.count }))]} />
    <ContentSection title="Executive findings"><p>The release contains 932 discrete records retrieved {formatCoverageDate(facts.retrievedAt)}. Karachi, Lahore and Islamabad are the three largest derived city groups among the catalogue pages. These totals describe retained source records and should not be read as continuous geographic coverage, live-site totals or service-quality rankings.</p></ContentSection>
    <EvidenceNote>The source review was performed {formatCoverageDate(facts.reviewedAt)}. Jazz and Zong machine-readable records matched the release counts. The original Ufone source URL was unavailable, so its dated snapshot remains published with that limitation visible.</EvidenceNote>
    <ContentSection title="Provider source audit" tone="band"><div className="overflow-x-auto"><table className="w-full min-w-[48rem] text-left text-sm"><thead><tr className="border-b border-slate-300"><th className="py-3 pr-4">Operator</th><th className="py-3 pr-4">Release records</th><th className="py-3 pr-4">Official source</th><th className="py-3">Review result</th></tr></thead><tbody className="divide-y divide-slate-200">{SITE_DATASET.providers.map((provider) => <tr key={provider.name} className="align-top"><th className="py-4 pr-4">{provider.name}</th><td className="py-4 pr-4 font-mono">{provider.count}</td><td className="py-4 pr-4"><SourceLink href={provider.sourceUrl}>{provider.sourceName}</SourceLink></td><td className="py-4 leading-6">{provider.sourceReview}</td></tr>)}</tbody></table></div></ContentSection>
    <ContentSection title="Largest city groups"><div className="grid gap-px border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{cities.map((city) => <article key={city.slug} className="bg-white p-5"><p className="font-mono text-2xl font-bold text-slate-950">{city.totalSites}</p><h3 className="mt-1 font-bold text-slate-800">{city.name}</h3><p className="mt-2 text-xs leading-5">Jazz {city.operatorCounts.Jazz}, Zong {city.operatorCounts.Zong}, Ufone / Onic {city.operatorCounts["Ufone / Onic"]}</p></article>)}</div></ContentSection>
    <ContentSection title="Method and limitations" tone="band"><p>5GPak retains operator names, record identifiers, source URLs and accuracy notes in GeoJSON. Jazz and Zong records use provider-published coordinates. Ufone / Onic locations were geocoded from provider material and are approximate. City names are derived for catalogue summaries; the map marker remains the evidence surface for individual records.</p><p className="mt-3">The release does not independently survey towers or model radio propagation. It excludes community reports and Reddit speed samples from these provider totals because those layers use different evidence standards.</p></ContentSection>
    <ContentSection title="Continue the analysis"><RelatedLinks links={[{ href: "/coverage", title: "Coverage by city", text: "Open the index of major city evidence pages." }, { href: "/compare/jazz-vs-zong-5g-pakistan", title: "Jazz vs Zong", text: "Compare retained records without a quality claim." }, { href: "/methodology", title: "Full methodology", text: "Review precision, provenance and update rules." }]} /></ContentSection>
  </CoveragePageFrame>;
}
