import { NextResponse } from "next/server";
import { OutageSubmissionSchema } from "@/features/network-status/schemas/outage.schema";
import { submitOutageReport } from "@/server/network-status/submitOutage";
import { supabaseOutageRepository } from "@/server/network-status/repository";
import { hashIp } from "@/server/reports/ipHash";
import { haversineDistanceKm } from "@/lib/haversine";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
function ip(req: Request) { return (req.headers.get("x-vercel-forwarded-for") ?? req.headers.get("x-forwarded-for") ?? req.headers.get("x-real-ip") ?? "0.0.0.0").split(",")[0].trim(); }
export async function POST(req: Request) { let raw: unknown; try { raw = await req.json(); } catch { return NextResponse.json({ ok: false, reason: "Invalid JSON." }, { status: 400 }); } const parsed = OutageSubmissionSchema.safeParse(raw); if (!parsed.success) return NextResponse.json({ ok: false, reason: "Invalid availability report." }, { status: 400 }); const salt = process.env.SUPABASE_IP_HASH_SALT; if (!salt) return NextResponse.json({ ok: false, reason: "Reports are temporarily unavailable." }, { status: 503 }); const lat = Number(req.headers.get("x-vercel-ip-latitude")); const lng = Number(req.headers.get("x-vercel-ip-longitude")); const far = Number.isFinite(lat) && Number.isFinite(lng) && haversineDistanceKm(lat, lng, parsed.data.latitude, parsed.data.longitude) > 300; try { const result = await submitOutageReport({ submission: parsed.data, ipHash: hashIp(ip(req), salt), ipRegionFar: far, repository: supabaseOutageRepository }); return NextResponse.json(result, { status: result.ok ? 201 : /many|blocked/i.test(result.reason) ? 429 : 400 }); } catch { return NextResponse.json({ ok: false, reason: "Something went wrong. Please try again." }, { status: 500 }); } }
