import { LegalLayout, LegalList, LegalSection } from "@/components/LegalDocument";

export const metadata = { title: "Terms of Use | 5GPak" };

export default function TermsPage() {
  return <LegalLayout eyebrow="LEGAL" title="Terms of Use" intro="These terms govern access to and use of 5GPak. By using the platform or submitting a report, you agree to these terms.">
    <LegalSection title="1. The service"><p className="mt-2">5GPak presents community-contributed coverage, speed, site, and network-availability information for general information and research. It is independent of Jazz, Zong, Ufone/Onic, and other operators unless we expressly say otherwise. Community signals are not operator-confirmed outage notices, technical guarantees, or emergency guidance.</p></LegalSection>
    <LegalSection title="2. Eligibility and acceptable use"><p className="mt-2">You may use 5GPak lawfully and for personal, research, or legitimate organisational purposes. You must not:</p><LegalList><li>Submit knowingly false, misleading, duplicated, automated, or manipulated reports.</li><li>Attempt to bypass rate limits, security controls, geographic restrictions, or access controls.</li><li>Probe, disrupt, overload, scrape at scale, reverse engineer, or interfere with the service except as permitted by law.</li><li>Upload or submit personal, confidential, unlawful, hateful, threatening, infringing, or harmful material.</li><li>Use the platform to make decisions where inaccurate network information could cause injury, emergency harm, or material loss.</li></LegalList></LegalSection>
    <LegalSection title="3. Community submissions"><p className="mt-2">You are responsible for the accuracy and legality of every report, bug report, and suggestion you submit. You grant 5GPak a non-exclusive, worldwide, royalty-free right to store, analyse, adapt, aggregate, and display your submission solely to operate, improve, secure, and promote the service. We may remove, hide, de-prioritise, or refuse submissions at our discretion to preserve quality and safety.</p></LegalSection>
    <LegalSection title="4. Data accuracy and no reliance"><p className="mt-2">Maps, statistics, and status indicators are estimates based on limited, changing community data and third-party sources. Coverage and performance vary by device, plan, location, time, building materials, weather, congestion, and many other factors. Verify critical information directly with your operator. Do not rely on 5GPak for emergency communications; use your operator, emergency services, or another reliable channel.</p></LegalSection>
    <LegalSection title="5. Intellectual property"><p className="mt-2">The 5GPak name, interface, original content, and software are protected by applicable intellectual-property laws. Third-party map, search, and network data remain subject to their respective licences and terms. You may not copy, resell, republish, or create a competing data service from the platform&apos;s content without written permission, except where applicable law permits it.</p></LegalSection>
    <LegalSection title="6. Availability and changes"><p className="mt-2">We may modify, suspend, or discontinue any part of the service, including data sources, features, or submission limits, without notice when reasonably necessary. We do not guarantee continuous availability, completeness, or error-free operation.</p></LegalSection>
    <LegalSection title="7. Disclaimers and limitation of liability"><p className="mt-2">To the maximum extent permitted by applicable law, 5GPak is provided “as is” and “as available,” without warranties of any kind. 5GPak and its operators are not liable for indirect, incidental, special, consequential, or punitive damages, or losses arising from use of, inability to use, or reliance on the platform. Nothing in these terms excludes liability that cannot lawfully be excluded.</p></LegalSection>
    <LegalSection title="8. Suspension and enforcement"><p className="mt-2">We may suspend or block access, device fingerprints, IP-derived identifiers, or submissions where we reasonably suspect abuse, unlawful activity, a security threat, or a breach of these terms. We may preserve and disclose relevant information where required by law or necessary to protect the service and its users.</p></LegalSection>
    <LegalSection title="9. Governing law and updates"><p className="mt-2">These terms are governed by the applicable laws of Pakistan, subject to mandatory consumer or privacy protections. Any dispute will be handled by courts with appropriate jurisdiction in Pakistan unless applicable law requires otherwise. We may update these terms; continued use after the effective date of an update means you accept the revised terms.</p></LegalSection>
  </LegalLayout>;
}
