import { LegalLayout, LegalList, LegalSection } from "@/components/LegalDocument";

export const metadata = { title: "Privacy Policy | 5GPak" };

export default function PrivacyPage() {
  return <LegalLayout eyebrow="LEGAL" title="Privacy Policy" intro="This policy explains how 5GPak handles information when you browse the platform or voluntarily contribute a coverage, speed, status, bug, or feature-suggestion report.">
    <LegalSection title="1. Who we are and scope"><p className="mt-2">5GPak is an independent, community-data platform for Pakistan&apos;s mobile-network coverage, speed, and availability signals. We are not a mobile-network operator and do not provide emergency communications. This policy applies to 5GPak&apos;s website and related report forms.</p></LegalSection>
    <LegalSection title="2. Information we process"><p className="mt-2">We collect the minimum information needed to operate the service, protect it from abuse, and present aggregated network insights.</p><LegalList><li><strong>Voluntary reports:</strong> selected operator, network generation, availability status, report time, accuracy indicator, and—only when you submit a location-based report—the latitude and longitude you provide or permit your browser to provide. Speed reports may include the speed, latency, and technical result details you submit.</li><li><strong>Anti-abuse data:</strong> a device fingerprint and a one-way salted hash of your IP address. We use these to apply rate limits, detect duplicate or abusive submissions, and protect the platform. We do not display them publicly.</li><li><strong>Bug reports and suggestions:</strong> the structured text, category, affected page, anonymous device fingerprint, and limited browser context needed to investigate the issue.</li><li><strong>Technical and usage data:</strong> standard request, security, and diagnostic data processed by our hosting and analytics providers, such as browser type, pages viewed, timestamps, and error information.</li></LegalList><p className="mt-3">We do not ask for accounts, names, phone numbers, SIM or IMEI numbers, subscriber records, payment details, screenshots, or public profile information.</p></LegalSection>
    <LegalSection title="3. How we use information"><LegalList><li>Provide coverage, speed, status, history, and insight features.</li><li>Aggregate reports into area-level community signals and improve their quality.</li><li>Prevent fraud, rate-limit submissions, investigate security incidents, and maintain service reliability.</li><li>Review bugs and feature suggestions, communicate essential policy or service changes where a contact channel is available, and comply with applicable law.</li></LegalList><p className="mt-3">Where consent is required, submitting a voluntary report or enabling browser location is your choice. You can use much of the site without submitting a report or granting location access.</p></LegalSection>
    <LegalSection title="4. Location and public map visibility"><p className="mt-2">Precise submitted coordinates are kept server-side. The public map and dashboards show aggregated cells or incident summaries, not your individual coordinate, IP hash, or device fingerprint. Location is used to place your report in an area and evaluate community agreement. Browser location permission can be withdrawn in your browser settings.</p></LegalSection>
    <LegalSection title="5. Cookies, analytics, and third parties"><p className="mt-2">We use essential browser storage for interface and report-flow preferences. Vercel Analytics may process privacy-preserving usage information to help us understand site performance. Our service providers may process data on our behalf, including Vercel for hosting/security, Supabase for database services, Carto/OpenStreetMap-based tiles for maps, Photon for location search, and Speedtest.net when you voluntarily resolve a Speedtest result. Their services are governed by their own terms and privacy notices.</p></LegalSection>
    <LegalSection title="6. Sharing and international processing"><p className="mt-2">We do not sell personal information. We share information only with service providers that operate the platform, in aggregated or de-identified form for public insights, or when disclosure is reasonably necessary to protect rights, safety, security, or comply with a lawful request. Infrastructure providers may process information outside Pakistan.</p></LegalSection>
    <LegalSection title="7. Retention and security"><p className="mt-2">We retain report and security data only for as long as reasonably needed for network research, service operation, anti-abuse controls, dispute handling, and legal obligations. We may retain non-identifying aggregated statistics longer. We use technical and organisational safeguards, including access controls, row-level database protection, rate limits, and encrypted transport. No internet service can promise absolute security.</p></LegalSection>
    <LegalSection title="8. Your choices and requests"><p className="mt-2">You may decline location permission and choose not to submit reports. To request access, correction, deletion, or raise a privacy concern about information reasonably linked to your submission, contact us using the address below. We may need limited information to verify the request and may retain data where legally required or necessary for security and fraud prevention.</p></LegalSection>
    <LegalSection title="9. Children and changes"><p className="mt-2">5GPak is not directed at children. Do not submit information about anyone under the age at which they can legally consent in their location. We may update this policy as the service or legal requirements change; the effective date above will be updated when we do.</p></LegalSection>
    <LegalSection title="10. Governing context"><p className="mt-2">We aim to operate consistently with applicable Pakistani law, including relevant electronic-crime and telecommunications requirements. This policy is an operational transparency notice, not a waiver of rights or a substitute for legal advice.</p></LegalSection>
  </LegalLayout>;
}
